// Lista completa de DDDs do Brasil, com sigla do estado e descrição da região/cidade principal
export const dddInfo = {
  // Norte
  '68': { sigla: 'AC', descricao: 'Acre (todos os municípios)' },
  '96': { sigla: 'AP', descricao: 'Amapá (todos os municípios)' },
  '92': { sigla: 'AM', descricao: 'Manaus e região' },
  '97': { sigla: 'AM', descricao: 'Tefé, Coari e região' },
  '69': { sigla: 'RO', descricao: 'Rondônia (todos os municípios)' },
  '95': { sigla: 'RR', descricao: 'Roraima (todos os municípios)' },
  '63': { sigla: 'TO', descricao: 'Tocantins (todos os municípios)' },
  // Nordeste
  '82': { sigla: 'AL', descricao: 'Alagoas (todos os municípios)' },
  '71': { sigla: 'BA', descricao: 'Região Metropolitana de Salvador' },
  '73': { sigla: 'BA', descricao: 'Itabuna, Ilhéus e região' },
  '74': { sigla: 'BA', descricao: 'Juazeiro e região' },
  '75': { sigla: 'BA', descricao: 'Feira de Santana e região' },
  '77': { sigla: 'BA', descricao: 'Vitória da Conquista e região' },
  '85': { sigla: 'CE', descricao: 'Região Metropolitana de Fortaleza' },
  '88': { sigla: 'CE', descricao: 'Juazeiro do Norte e região' },
  '98': { sigla: 'MA', descricao: 'Região Metropolitana de São Luís' },
  '99': { sigla: 'MA', descricao: 'Região de Imperatriz' },
  '83': { sigla: 'PB', descricao: 'Paraíba (todos os municípios)' },
  '81': { sigla: 'PE', descricao: 'Região Metropolitana de Recife' },
  '87': { sigla: 'PE', descricao: 'Petrolina e região' },
  '86': { sigla: 'PI', descricao: 'Região de Teresina' },
  '89': { sigla: 'PI', descricao: 'Região de Picos e Floriano' },
  '84': { sigla: 'RN', descricao: 'Rio Grande do Norte (todos os municípios)' },
  '79': { sigla: 'SE', descricao: 'Sergipe (todos os municípios)' },
  // Centro-Oeste
  '61': { sigla: 'DF', descricao: 'Brasília e região' },
  '62': { sigla: 'GO', descricao: 'Região Metropolitana de Goiânia' },
  '64': { sigla: 'GO', descricao: 'Rio Verde e região' },
  '65': { sigla: 'MT', descricao: 'Região Metropolitana de Cuiabá' },
  '66': { sigla: 'MT', descricao: 'Rondonópolis e região' },
  '67': { sigla: 'MS', descricao: 'Mato Grosso do Sul (todas as cidades)' },
  '63': { sigla: 'TO', descricao: 'Tocantins (todas as cidades)' },
  // Sudeste
  '27': { sigla: 'ES', descricao: 'Região Metropolitana de Vitória' },
  '28': { sigla: 'ES', descricao: 'Cachoeiro de Itapemirim e região' },
  '31': { sigla: 'MG', descricao: 'Região Metropolitana de Belo Horizonte' },
  '32': { sigla: 'MG', descricao: 'Juiz de Fora e região' },
  '33': { sigla: 'MG', descricao: 'Governador Valadares e região' },
  '34': { sigla: 'MG', descricao: 'Uberlândia e região' },
  '35': { sigla: 'MG', descricao: 'Poços de Caldas, Pouso Alegre, Varginha e região' },
  '37': { sigla: 'MG', descricao: 'Divinópolis, Itaúna e região' },
  '38': { sigla: 'MG', descricao: 'Montes Claros e região' },
  '21': { sigla: 'RJ', descricao: 'Região Metropolitana do Rio de Janeiro' },
  '22': { sigla: 'RJ', descricao: 'Campos dos Goytacazes' },
  '24': { sigla: 'RJ', descricao: 'Volta Redonda, Petrópolis e região' },
  '11': { sigla: 'SP', descricao: 'Região Metropolitana de São Paulo' },
  '12': { sigla: 'SP', descricao: 'São José dos Campos e região' },
  '13': { sigla: 'SP', descricao: 'Baixada Santista' },
  '14': { sigla: 'SP', descricao: 'Bauru, Jaú, Marília, Botucatu e região' },
  '15': { sigla: 'SP', descricao: 'Sorocaba e região' },
  '16': { sigla: 'SP', descricao: 'Ribeirão Preto, São Carlos, Araraquara e região' },
  '17': { sigla: 'SP', descricao: 'São José do Rio Preto e região' },
  '18': { sigla: 'SP', descricao: 'Presidente Prudente, Araçatuba e região' },
  '19': { sigla: 'SP', descricao: 'Região Metropolitana de Campinas' },
  // Sul
  '41': { sigla: 'PR', descricao: 'Região Metropolitana de Curitiba' },
  '42': { sigla: 'PR', descricao: 'Ponta Grossa e região' },
  '43': { sigla: 'PR', descricao: 'Londrina e região' },
  '44': { sigla: 'PR', descricao: 'Maringá e região' },
  '45': { sigla: 'PR', descricao: 'Cascavel e região' },
  '46': { sigla: 'PR', descricao: 'Francisco Beltrão, Pato Branco e região' },
  '51': { sigla: 'RS', descricao: 'Região Metropolitana de Porto Alegre' },
  '53': { sigla: 'RS', descricao: 'Pelotas e região' },
  '54': { sigla: 'RS', descricao: 'Caxias do Sul e região' },
  '55': { sigla: 'RS', descricao: 'Santa Maria e região' },
  '47': { sigla: 'SC', descricao: 'Joinville, Blumenau, Balneário Camboriú e região' },
  '48': { sigla: 'SC', descricao: 'Florianópolis e Criciúma' },
  '49': { sigla: 'SC', descricao: 'Chapecó, Lages e região' },
}; 